### ISSUE TITLE
wdnmd.sp这个文件编译 是否需要其他支持？直接编译虽然不报错，但是编译出来的smx在插件列表报错且无法使用

### ISSUE THREAD

**Issue by sunencheng** [HMBSbige/SouceModPlugins#2]
18 <Error> "Wdnmd" (1.2) by Disappear9&HMBSbige插件列表报错
这个要怎么解决？
另外请教下大佬，你是用什么工具反编译smx的？

**Comment by HMBSbige** [comment]
自行解决吧，我也不知道什么原因，我这边直接编译没什么问题

**Comment by HMBSbige** [comment]
盲猜没放 gamedata 的数据
